version: "2.1"

services:

  db:
    image: postgres
    container_name: mfi-postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 1m30s
      retries: 10
    networks:
      - db

  backend:
    build: ./backend
    container_name: mfi-backend
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - ALLOWED_HOST=*
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -v --silent http://localhost:8000 2>&1 | grep 200"]
      interval: 40s
      timeout: 30s
      retries: 5
    networks:
      - backend
      - db
  
  frontend:
    build: ./front
    container_name: mfi-frontend
    command: npm start
    environment:
      - REACT_APP_API_HOST=localhost
      - REACT_APP_API_PORT=8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -v --silent http://localhost:3000 2>&1 | grep 200"]
      interval: 20s
      timeout: 1m
      retries: 5
    networks:
      - frontend
    
  nginx:
    image: nginx
    container_name: mfi-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/uwsgi_params:/usr/share/nginx/uwsgi_params
    command: [nginx-debug, '-g', 'daemon off;']
    environment:
      - NGINX_HOST=mfi.fr
      - NGINX_PORT=8080
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    ports:
    - "8080:8080"
    networks:
      - backend
      - frontend


networks:
  frontend:
  backend:
  db:
